### ISSUE TITLE
No module named 'hijri'

### ISSUE THREAD

**Issue by Shah9il** [hmtanbir/banglaHijri#1]
>>> import hijricalendar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Personal\Python\hdi_django\hdi_site\hdi_env_py3.10.0\lib\site-packages\hijricalendar\__init__.py", line 4, in <module>
    from umalqurra.hijri_date import HijriDate
  File "D:\Personal\Python\hdi_django\hdi_site\hdi_env_py3.10.0\lib\site-packages\umalqurra\hijri_date.py", line 10, in <module>
    from hijri import Umalqurra
ModuleNotFoundError: No module named 'hijri'
>>> import hijricalendar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Personal\Python\hdi_django\hdi_site\hdi_env_py3.10.0\lib\site-packages\hijricalendar\__init__.py", line 4, in <module>
    from umalqurra.hijri_date import HijriDate
  File "D:\Personal\Python\hdi_django\hdi_site\hdi_env_py3.10.0\lib\site-packages\umalqurra\hijri_date.py", line 10, in <module>
    from hijri import Umalqurra
ModuleNotFoundError: No module named 'hijri'
>>> import hijri
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: **No module named 'hijri'**

**Comment by hmtanbir** [comment]
@Shah9il could you please add more details and in which scenario you got the issue ?
